### ISSUE TITLE
Add strings for internationalization

### ISSUE THREAD

**Issue by paperdigits** [xmlrocks/dita-ot-pdf-css-page#10]
I've added strings to the plugin. Please find the patch attached.
[0001-Added-strings.zip](https://github.com/xmlrocks/dita-ot-pdf-css-page/files/720514/0001-Added-strings.zip)

**Comment by v-kushnir** [comment]
Hi @paperdigits,

I've added templates for "TOC" and "Index" localization.
Since DITA-OT already has default values for "TOC" and "Index" variables, we wouldn't add them to plugin transformation. But you may add new string files for your own customization if it is required. 

Volodymyr

**Comment by paperdigits** [comment]
Thanks!
