### ISSUE TITLE
Error: Target "transform.topic2fo.flagging" does not exist

### ISSUE THREAD

**Issue by gtourtellot** [xmlrocks/dita-ot-pdf-css-page#11]
After installing doing a fresh install of dita-ot-2.4.4 and then installing the plugin dita-ot-pdf-css-page, running dita gives this error:

Error: Target "transform.topic2fo.flagging" does not exist in the project "DOST". It is used from target "pdf-css-page.transform.topic2fo".

**Comment by v-kushnir** [comment]
Hi @gtourtellot,

I'm going to check out this issue soon and get back to you with an update.

Volodymyr

**Comment by v-kushnir** [comment]
Hi @gtourtellot, 

I've updated the plugin and now you can use it with DITA-OT 2.4.4.

Thanks!
