### ISSUE TITLE
Plugin extension transform name over ride

### ISSUE THREAD

**Issue by paperdigits** [xmlrocks/dita-ot-pdf-css-page#12]
I've been trying to make a plugin that defines a new transtype and has a few template over rides and calls the pdf-css-page plugin, but I've been unable to do so successfully.

Can you please point me in the right direction?

**Comment by ibarinova** [comment]
Hello @paperdigits ,

Could you please give us more information? How are you extending pdf-css-page XSL transformation? Are you using existing extension points or import this XSL in your stylesheet?

Thanks,
Irina

**Comment by paperdigits** [comment]
Hi @ibarinova 

I was following the instructions at http://www.dita-ot.org/2.3/dev_ref/plugin-newtranstype.html 

Right now, I have a plugin that over rides a few templates in the `pdf-css-page` plugin. When I build, I uses the `pdf-css-page` transtype. This is good and work well, but I have many many different output styles that I need to make. The extent of my overrides are pretty simple: new cover page elements, add a back cover, and inject some custom CSS.

So I'd just like to make my override plugin also have a separate transtype so I can have many different override plugins that don't clobber each other. 

Thanks for your help!

**Comment by ibarinova** [comment]
Hello @paperdigits,
 
I'm agree with you, that ti is better to add separate plugins for different customizations. 
The best approach is DO NOT modify original plugin and use extension points for them.

If you need just to modify some  XSL templates, you can use existing extension point 'xsl.pdf-css-page.override'. 
Please follow next steps to implement this feature:
1. Create new plugin directory.
2. Create new plugin.xml file. It's structure could be pretty simple. As far as I see, you know, how to add net transformation type. Please do this in your plugin.xml.
3. Then, if you want to use pdf-css-page plugin and override it, please add following code to the same file:
```
    <require plugin="rocks.xml.pdf.css.page"/>
    <feature extension="xsl.pdf-css-page.override" file="xsl/test.xsl"/>
```
Now you've got something like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<plugin id="test.plugin,com">
    <require plugin="rocks.xml.pdf.css.page"/>
    <feature extension="xsl.pdf-css-page.override" file="xsl/test.xsl"/>

    <feature extension="dita.conductor.transtype.check" value="test"/>
    <feature extension="dita.transtype.print" value="test"/>
</plugin>
```
4. As you can see above, you should add XSL file to your plugin directory (in our example it is test.xsl in xsl dir). Below is an example of sample XSLT customization:
```
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

    <xsl:template name="create-book-title">
        <div class="book-title">
            <xsl:text>TEST string on cover page before title</xsl:text>
            <h1 class="title-page">
                <xsl:call-template name="gen-book-title"/>
            </h1>
        </div>
    </xsl:template>
    
</xsl:stylesheet>
```
Final structure of new plugin is following:
```
test.plugin.com
|__ xsl
|     |__ test.xsl
|__ plugin.xml
```
That is it! Plugin are ready for working. Just two files and two folders :)

Please, let me know, if you have any questions.

Best regards,
Irina

**Comment by paperdigits** [comment]
@ibarinova Thank you for your reply!

I had done something very similar myself previously. 

I grabbed a fresh toolkit instance and the latest XML Rocks plugin, and followed your instructions, but I get the error:
```
Error: The following error occurred whiel executing this line:
Target "dita2mp-eoc-pdf" does not exist in the project "DOST"
```

This is with toolkit 2.3.3 and the transform name of my override is mp-eoc-pdf.

**Comment by ibarinova** [comment]
Hello @paperdigits ,

Please add following changes to your plugin:

1. Add new integrator.xml file to your plugin directory. 
It should have target with specific name which should match following pattern: '`dita2transtype`'. In my example it should be '`dita2test`'. Here you can call existed '`dita2pdf-css-page`' target. But before this
you should override pdf-css-page XSL transformation. It is better to do in separate initialization target.
Below is an example of the simplest integrator file:

```
<?xml version="1.0" encoding="UTF-8"?>
<project>
    <target name="dita2test" depends="dita2test.init, dita2pdf-css-page"/>

    <target name="dita2test.init">
        <property name="xsl.file" value="${dita.plugin.test.plugin.dir}${file.separator}xsl${file.separator}test.xsl"/>
    </target>
</project>
```
2. Add '`dita.conductor.target.relative`' feature to your plugin xml and remove '`xsl.pdf-css-page.override`' feature, We do not need at anymore, because we will import this XSLT from our customization file.
```
<?xml version="1.0" encoding="UTF-8"?>
<plugin id="test.plugin.com">
    <require plugin="rocks.xml.pdf.css.page"/>

    <feature extension="dita.conductor.target.relative" file="integrator.xml"/>

    <feature extension="dita.conductor.transtype.check" value="test"/>
    <feature extension="dita.transtype.print" value="test"/>
</plugin>
```
3. Import pdf-css-page XSL transformation in your customization XSL file. In my example it is test.xsl and it looks like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

    <xsl:import href="plugin:rocks.xml.pdf.css.page:xslt/dita2pdf-css-page-import.xsl"/>

    <xsl:template name="create-book-title">
        <div class="book-title">
            <xsl:text>TEST string on cover page before title</xsl:text>
            <h1 class="title-page">
                <xsl:call-template name="gen-book-title"/>
            </h1>
        </div>
    </xsl:template>

</xsl:stylesheet>
```

The final structure of plugin is following:
```
test.plugin.com
|__ xsl
|     |__ test.xsl
|__ integrator.xml
|__ plugin.xml
```
More information you can find [here ](http://www.dita-ot.org/dev/dev_ref/plugin-newtranstype.html) and [here](http://www.dita-ot.org/dev/dev_ref/using-plugin-URI-extension.html).

Please, let me know, if you have any question.

Best regards,
Irina

**Comment by paperdigits** [comment]
Hi Irina,

This is now mostly working. The last piece is that any images do not get copied to the TEMP directory, instead they're copied to OUT, so when antenna house builds the PDFs, the images are missing. 

I thought I could simply use `<feature extension="depend.preprocess.copy-image.pre" value="pdf-css-page.image.dir.init"/>` in my `plugin.xml` file, but this doesn't seem to work.

**Comment by ibarinova** [comment]
Hello @paperdigits,

'`pdf-css-page.image.dir.init`' target will work only if '`rocks.xml.pdf.css.page`' property was set.

So, please, add following string to your init target:
`<property name="rocks.xml.pdf.css.page" value="true"/>`

For example:
  ```
  <target name="dita2test.init">
        <property name="xsl.file" value="${dita.plugin.test.plugin.dir}${file.separator}xsl${file.separator}test.xsl"/>
        <property name="rocks.xml.pdf.css.page" value="true"/>
    </target>
```

This should help.

Best regards,
Irina

**Comment by paperdigits** [comment]
That makes it work, thank you so much!
