### ISSUE TITLE
Build failed on AH formatter v6.3, DITA OT 2.2.3, Oxygen 18

### ISSUE THREAD

**Issue by aidanreilly** [xmlrocks/dita-ot-pdf-css-page#5]
[echo] [WARN]: You are using Antennahouse. Please notice that Index may not work properly.

I note the plugin also fails in Oxygen 18 with AH...

Is this a known issue?

**Comment by v-kushnir** [comment]
Hi @aidanreilly,

Thank you so much for being interested in our plugin. 
We were not aware of the incompatibility. I'm going to check out this issue soon and get back to you with an update on this.

- Volodymyr

**Comment by v-kushnir** [comment]
Hi @aidanreilly,

I've checked the transformation using Oxygen 18 and AH Formatter V6.3. The issue that I found is the error in the merged HTML file after DITA-OT transformation. There was the incorrect style for a div tag. I've fixed it. 

Please, check out the new build. If you still get an error, please let us know: http://xml.rocks/#contact-us.

Volodymyr
