### ISSUE TITLE
Custom title page

### ISSUE THREAD

**Issue by paperdigits** [xmlrocks/dita-ot-pdf-css-page#6]
This plugin looks very convenient, than you!

I'm trying to make a custom title page, but I can't seem to find an extension point to override the templates in this plugin. 

Do you have any advice on how to customize this plugin?

Also how can I keep the intermediate HTML file before it is sent to the PDF formatter?

**Comment by v-kushnir** [comment]
Hi @paperdigits,

1. At this moment there is no extension point to override the templates in this plugin. But it should be very useful, so I'll add it ASAP and get back to you.

2. To keep the intermediate HTML file before it is sent to the PDF formatter you can set temp directory ('-temp /path/to/temp/directory') and set property -Dclean-temp.skip=true. Then you can find merged XHTML file inside this directory.  

- Volodymyr

**Comment by paperdigits** [comment]
Thanks @v-kushnir, I'll keep an eye out for the changes!

**Comment by v-kushnir** [comment]
Hi @paperdigits, 

I've added the new extension-point to override plugin XSL templates. You can use it by id "xsl.pdf-css-page.override". 

Could you please let me know if it resolves your issue?

Volodymyr

**Comment by paperdigits** [comment]
Yes, this does work pretty well, thank you!

I'm trying to read in the first topic in the map and use that as the title page, any suggestion on how to go about that?
