### ISSUE TITLE
Wrap body content in <div class="body-text>

### ISSUE THREAD

**Issue by paperdigits** [xmlrocks/dita-ot-pdf-css-page#7]
Since this plugin offers a wrapper for the title page and TOC, it'd be nice if the body content was also wrapped in a div as well. This would facilitate things like using CSS to reset the page counter after the TOC. It'd also allow for one to use a CSS named page to work with the CSS paged media stuff.

**Comment by v-kushnir** [comment]
Hi @paperdigits,

I've added body content wrapper to the merged XHTML file. Please, check it out and let me know if it resolves your issue.

Volodymyr

**Comment by paperdigits** [comment]
Works for me, thanks!
