### ISSUE TITLE
Styles in commonltr.css can not be restyled using Antenna House

### ISSUE THREAD

**Issue by paperdigits** [xmlrocks/dita-ot-pdf-css-page#8]
commonltr.css is written into the head of the XHTML file and seems to be processed last by Antenna House. The result is that I can not over ride styling present in commonltr.css when specifying my own CSS file at built time using `-Dcss.file`. 

If I remove the content leaving an empty file (or remove the file), then the changes from my custom CSS file are visible in the PDF.

**Comment by v-kushnir** [comment]
Hi @paperdigits,

It seems to be Antenna House bug. I've checked out the documentation related to this issue and found the information that property '-s' (which we are using in out build.xml) will be the last user stylesheet file. But looks like it doesn't work.

There is another way to handle it. You can use another property to customize the CSS file. Please, try "-Duser.csspath" to set your custom CSS file. The transformation will create a <link> tag inside the merged XHTML file with higher priority then commonltr.css.

Please, let me know if it works for you. Thanks. 

Volodymyr

**Comment by paperdigits** [comment]
That does work, thanks. I've opened an inquiry with Antenna House.

**Comment by paperdigits** [comment]
Antenna House said they just follow the W3C CSS standard, which gives more weight to the "author" (embedded) stylesheet than to the "user" stylesheet (the one passed via `-s`). Antenna House says to override styles `!important` should be used. So `-Duser.csspath` is a very nice option to have.

**Comment by v-kushnir** [comment]
Thanks for the update, @paperdigits.
